# Generated by Django 5.2.4 on 2025-08-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('O', 'Other'), ('E', 'Entertainment'), ('G', 'Grocery'), ('H', 'Housing'), ('U', 'Utilities'), ('T', 'Transportation'), ('M', 'Memberships'), ('P', 'Personal')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Transaction Date'),
        ),
    ]
