# Generated by Django 5.2.4 on 2025-08-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_deposit_alter_expense_category_alter_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='name',
        ),
        migrations.AddField(
            model_name='deposit',
            name='date',
            field=models.DateField(default=0, verbose_name='Deposit Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
