# Generated by Django 5.2.4 on 2025-08-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_deposit_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='amount',
            new_name='name',
        ),
    ]
