# Generated by Django 5.2.4 on 2025-08-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_amount_deposit_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
