# Generated by Django 5.2.4 on 2025-08-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_deposit_alter_expense_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='date',
        ),
    ]
